# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Sunitha Narayan'
name:             'Sunitha Narayan'
#tagline:          ''
description:      'Language technologist and software developer'
#url:              http://vakila.github.io/
baseurl:
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Sunitha Narayan'
  url:            hyde
  email:          'anjanavakil@gmail.com'
  github:         'https://github.com/sunithan29'
  facebook:       'http://www.facebook.com/anjana.vakil'
  twitter:        'https://twitter.com/AnjanaVakil'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/anjanavakil '

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sunithan29/hyde

# Collections
collections:
  - projects
  - Education

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
